import { jsPDF } from 'jspdf';

export const generatePDF = (invoiceData) => {
  const doc = new jsPDF();
  
  // Custom font/style
  doc.setFont("helvetica");

  // Header background (Black)
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, 210, 40, 'F');
  
  // Gold Logo Placeholder / Title
  doc.setTextColor(212, 175, 55);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 15, 25);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice.ai Premium Platform`, 120, 25);

  // Billing Details (Black Text on White Page)
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Billed To:`, 15, 60);

  doc.setFont("helvetica", "normal");
  doc.text(invoiceData.customerName || "Vaidya AI Admin", 15, 70);
  
  doc.setFont("helvetica", "bold");
  doc.text(`From:`, 120, 60);
  doc.setFont("helvetica", "normal");
  doc.text(invoiceData.vendorName || "Vendor Name", 120, 70);

  doc.text(`Invoice No:`, 120, 80);
  doc.text(invoiceData.invoiceNumber || "N/A", 150, 80);
  doc.text(`Date:`, 120, 90);
  doc.text(invoiceData.date || "N/A", 150, 90);

  // Table Line
  doc.setDrawColor(212, 175, 55); // Gold line
  doc.setLineWidth(1);
  doc.line(15, 105, 195, 105);
  
  // Table Headers
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Item Description", 15, 115);
  doc.text("Qty", 110, 115);
  doc.text("Price", 140, 115);
  doc.text("Total", 175, 115);

  doc.setLineWidth(0.5);
  doc.line(15, 120, 195, 120);

  let startY = 130;
  doc.setFont("helvetica", "normal");
  (invoiceData.items || []).forEach(item => {
    doc.text(item.name || "Item", 15, startY);
    doc.text(String(item.quantity) || "1", 110, startY);
    doc.text(`$${Number(item.price || 0).toFixed(2)}`, 140, startY);
    doc.text(`$${Number(item.total || 0).toFixed(2)}`, 175, startY);
    startY += 10;
  });

  doc.line(15, startY, 195, startY);

  // Total
  startY += 10;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(212, 175, 55);
  doc.setFontSize(14);
  doc.text(`Grand Total:`, 130, startY);
  doc.text(`$${Number(invoiceData.totalAmount || 0).toFixed(2)}`, 165, startY);

  // Footer Message
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text("Thank you for your business. Generated by AI.", 105, 280, null, null, "center");

  doc.save(`Invoice_${invoiceData.invoiceNumber || 'New'}.pdf`);
};
